In [1]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import roc_auc_score

In [2]:
# Read 
senate = pd.read_csv("senate_analytical.csv")

# Randomize the data
senate = shuffle(senate)

senate.head()

Cand_Id Cand_Incumbent_Challenger_Open_Seat            Cand_Name  \
1236  S0TX00217                                OPEN  PITTENGER, LELA MAE   
1584  S4NJ00201                                OPEN           HOLT, RUSH   
487   S0IL00394                                OPEN      DORSEY, MICHAEL   
2152  S6NY00433                          CHALLENGER         MERCED, ALEX   
255   S2TX00106                           INCUMBENT         CORNYN, JOHN   

     Cand_Office Cand_State  GE WINNER INDICATOR  Individual_Contribution  \
1236           S         TX                    0                  34764.0   
1584           S         NJ                    0                1224042.0   
487            S         IL                    0                      0.0   
2152           S         NY                    0                  12461.0   
255            S         TX                    1               10061260.0   

      Other_Committee_Contribution  Party_Committee_Contribution  \
1236                           0.0                         250.0   
1584                       19756.0                         500.0   
487                            0.0                           0.0   
2152                        2000.0                           0.0   
255                      2613361.0                           0.0   

      Total_Disbursement        ...          Cand_Office_St_SD  \
1236             51567.0        ...                          0   
1584           1744765.0        ...                          0   
487                107.0        ...                          0   
2152             14459.0        ...                          0   
255           16454518.0        ...                          0   

      Cand_Office_St_TN  Cand_Office_St_TX  Cand_Office_St_UT  \
1236                  0                  1                  0   
1584                  0                  0                  0   
487                   0                  0                  0   
2152                  0                  0                  0   
255                   0                  1                  0   

      Cand_Office_St_VA  Cand_Office_St_VT  Cand_Office_St_WA  \
1236                  0                  0                  0   
1584                  0                  0                  0   
487                   0                  0                  0   
2152                  0                  0                  0   
255                   0                  0                  0   

      Cand_Office_St_WI  Cand_Office_St_WV  Cand_Office_St_WY  
1236                  0                  0                  0  
1584                  0                  0                  0  
487                   0                  0                  0  
2152                  0                  0                  0  
255                   0                  0                  0  

[5 rows x 72 columns]

In [3]:
# Reading the test data
senate_test = pd.read_csv("test_analytical.csv")

# print(senate_test["Cand_Office_St"].value_counts())

y_test = senate_test["GE WINNER INDICATOR"]

test_states = senate_test["Cand_Office_St"]
X_test = senate_test.drop(columns=["Cand_Office_St","Cand_Office_Dist","Cand_Id","Cand_Incumbent_Challenger_Open_Seat","Cand_Name","Cand_Office","Cand_State","GE WINNER INDICATOR","Individual_Contribution","Other_Committee_Contribution","Party_Committee_Contribution","Total_Disbursement","Total_Receipt"])


print(X_test.shape)
X_test.columns

# y_test = y_test.astype(int)
X_test.head()

(483, 60)


top_individual_contribution  top_total_disbursement  \
0                            0                       0   
1                            0                       0   
2                            0                       0   
3                            0                       0   
4                            0                       0   

   top_other_comm_contribution  top_party_comm_contribution  in_state  \
0                            0                            0         1   
1                            0                            1         1   
2                            0                            1         1   
3                            0                            0         1   
4                            0                            0         1   

   incumbent  open  Cand_Party_Affiliation_DEM  Cand_Party_Affiliation_OTHER  \
0          0     1                           1                             0   
1          0     1                           0                             0   
2          0     1                           0                             1   
3          0     1                           1                             0   
4          0     1                           1                             0   

   Cand_Party_Affiliation_REP        ...          Cand_Office_St_ID  \
0                           0        ...                          0   
1                           1        ...                          0   
2                           0        ...                          0   
3                           0        ...                          0   
4                           0        ...                          0   

   Cand_Office_St_NH  Cand_Office_St_AR  Cand_Office_St_OK  Cand_Office_St_KS  \
0                  0                  0                  0                  0   
1                  0                  0                  0                  0   
2                  0                  0                  0                  0   
3                  0                  0                  0                  0   
4                  0                  0                  0                  0   

   Cand_Office_St_LA  Cand_Office_St_IL  Cand_Office_St_AL  Cand_Office_St_SD  \
0                  0                  0                  0                  0   
1                  0                  0                  0                  0   
2                  0                  0                  0                  0   
3                  0                  0                  0                  0   
4                  0                  0                  0                  0   

   Cand_Office_St_SC  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 60 columns]

### For 1 year data (2016)

In [4]:
senate_2016 = senate[senate["year"] == 2016].copy()

y = senate_2016["GE WINNER INDICATOR"]
X = senate_2016.drop(columns=["Cand_Id","Cand_Incumbent_Challenger_Open_Seat","Cand_Name","Cand_Office","Cand_State","GE WINNER INDICATOR","Individual_Contribution","Other_Committee_Contribution","Party_Committee_Contribution","Total_Disbursement","Total_Receipt","year"])

print(y.value_counts())
print(X.shape)
# y.head()

senate_2016.head()

0    448
1     38
Name: GE WINNER INDICATOR, dtype: int64
(486, 60)


Cand_Id Cand_Incumbent_Challenger_Open_Seat                Cand_Name  \
2152  S6NY00433                          CHALLENGER             MERCED, ALEX   
1870  S6CO00341                          CHALLENGER             ELLER, JERRY   
2171  S6OK04130                          CHALLENGER           BRADDY, SEAN D   
1940  S6HI00305                          CHALLENGER  GIUFFRE, JOHN M.(RAGHU)   
1915  S6FL00475                          CHALLENGER     BURKE, ROBERT INGRAM   

     Cand_Office Cand_State  GE WINNER INDICATOR  Individual_Contribution  \
2152           S         NY                    0                  12461.0   
1870           S         CO                    0                      0.0   
2171           S         OK                    0                  12508.0   
1940           S         HI                    0                      0.0   
1915           S         FL                    0                      0.0   

      Other_Committee_Contribution  Party_Committee_Contribution  \
2152                        2000.0                           0.0   
1870                           0.0                           0.0   
2171                           0.0                           0.0   
1940                           0.0                           0.0   
1915                           0.0                           0.0   

      Total_Disbursement        ...          Cand_Office_St_SD  \
2152             14459.0        ...                          0   
1870                 0.0        ...                          0   
2171             13241.0        ...                          0   
1940                 0.0        ...                          0   
1915                 0.0        ...                          0   

      Cand_Office_St_TN  Cand_Office_St_TX  Cand_Office_St_UT  \
2152                  0                  0                  0   
1870                  0                  0                  0   
2171                  0                  0                  0   
1940                  0                  0                  0   
1915                  0                  0                  0   

      Cand_Office_St_VA  Cand_Office_St_VT  Cand_Office_St_WA  \
2152                  0                  0                  0   
1870                  0                  0                  0   
2171                  0                  0                  0   
1940                  0                  0                  0   
1915                  0                  0                  0   

      Cand_Office_St_WI  Cand_Office_St_WV  Cand_Office_St_WY  
2152                  0                  0                  0  
1870                  0                  0                  0  
2171                  0                  0                  0  
1940                  0                  0                  0  
1915                  0                  0                  0  

[5 rows x 72 columns]

In [5]:
clf = RandomForestClassifier(n_estimators=200)
clf.fit(X,y)
X_test_1 = X_test.copy()
y_prob_1 = clf.predict_proba(X_test_1)[:,1]
print("Score: " + str(clf.score(X_test_1,y_test)))

Score: 0.9772256728778468


In [6]:
X_test_1["State"] = test_states
X_test_1["y_prob"] = y_prob_1

X_test_1["winner"] = 0
X_test_1.loc[X_test_1.groupby(['State'])["y_prob"].idxmax(),"winner"] = 1

print("AUC: " + str(roc_auc_score(y_test, y_prob_1)))
precision_recall_fscore_support(y_test, X_test_1["winner"])

AUC: 0.9876430976430977


(array([0.98663697, 0.79411765]),
 array([0.98444444, 0.81818182]),
 array([0.98553949, 0.80597015]),
 array([450,  33], dtype=int64))

### For 2 years data (2016 and 2014)

In [7]:
senate_2 = senate[(senate["year"] == 2016) | (senate["year"] == 2014)].copy()

y = senate_2["GE WINNER INDICATOR"]
X = senate_2.drop(columns=["Cand_Id","Cand_Incumbent_Challenger_Open_Seat","Cand_Name","Cand_Office","Cand_State","GE WINNER INDICATOR","Individual_Contribution","Other_Committee_Contribution","Party_Committee_Contribution","Total_Disbursement","Total_Receipt","year"])

# print(y.value_counts())
print(X.shape)

senate_2.head()

(904, 60)


Cand_Id Cand_Incumbent_Challenger_Open_Seat               Cand_Name  \
1584  S4NJ00201                                OPEN              HOLT, RUSH   
2152  S6NY00433                          CHALLENGER            MERCED, ALEX   
1496  S4MI00371                                OPEN    FULNER, ROBERT JAMES   
1503  S4MN00403                          CHALLENGER  TERRELL, KEVIN RICHARD   
1870  S6CO00341                          CHALLENGER            ELLER, JERRY   

     Cand_Office Cand_State  GE WINNER INDICATOR  Individual_Contribution  \
1584           S         NJ                    0                1224042.0   
2152           S         NY                    0                  12461.0   
1496           S         MI                    0                      0.0   
1503           S         MN                    0                   4343.0   
1870           S         CO                    0                      0.0   

      Other_Committee_Contribution  Party_Committee_Contribution  \
1584                       19756.0                         500.0   
2152                        2000.0                           0.0   
1496                           0.0                           0.0   
1503                           0.0                           0.0   
1870                           0.0                           0.0   

      Total_Disbursement        ...          Cand_Office_St_SD  \
1584           1744765.0        ...                          0   
2152             14459.0        ...                          0   
1496                 0.0        ...                          0   
1503             43054.0        ...                          0   
1870                 0.0        ...                          0   

      Cand_Office_St_TN  Cand_Office_St_TX  Cand_Office_St_UT  \
1584                  0                  0                  0   
2152                  0                  0                  0   
1496                  0                  0                  0   
1503                  0                  0                  0   
1870                  0                  0                  0   

      Cand_Office_St_VA  Cand_Office_St_VT  Cand_Office_St_WA  \
1584                  0                  0                  0   
2152                  0                  0                  0   
1496                  0                  0                  0   
1503                  0                  0                  0   
1870                  0                  0                  0   

      Cand_Office_St_WI  Cand_Office_St_WV  Cand_Office_St_WY  
1584                  0                  0                  0  
2152                  0                  0                  0  
1496                  0                  0                  0  
1503                  0                  0                  0  
1870                  0                  0                  0  

[5 rows x 72 columns]

In [8]:
clf = RandomForestClassifier(n_estimators=200)
clf.fit(X,y)
X_test_2 = X_test.copy()
y_prob_2 = clf.predict_proba(X_test_2)[:,1]
print("Score: " + str(clf.score(X_test_2,y_test)))

Score: 0.9668737060041408


In [9]:
X_test_2["State"] = test_states
X_test_2["y_prob"] = y_prob_2

X_test_2["winner"] = 0
X_test_2.loc[X_test_2.groupby(['State'])["y_prob"].idxmax(),"winner"] = 1

print("AUC: " + str(roc_auc_score(y_test, y_prob_2)))

precision_recall_fscore_support(y_test, X_test_2["winner"])

AUC: 0.9886195286195286


(array([0.98663697, 0.79411765]),
 array([0.98444444, 0.81818182]),
 array([0.98553949, 0.80597015]),
 array([450,  33], dtype=int64))

### For 3 years data (2016, 2014 and 2012)

In [10]:
senate_3 = senate[(senate["year"] == 2016) | (senate["year"] == 2014) | (senate["year"] == 2012)].copy()

y = senate_3["GE WINNER INDICATOR"]
X = senate_3.drop(columns=["Cand_Id","Cand_Incumbent_Challenger_Open_Seat","Cand_Name","Cand_Office","Cand_State","GE WINNER INDICATOR","Individual_Contribution","Other_Committee_Contribution","Party_Committee_Contribution","Total_Disbursement","Total_Receipt","year"])

# print(y.value_counts())
print(X.shape)

senate_3.head()

(1368, 60)


Cand_Id Cand_Incumbent_Challenger_Open_Seat               Cand_Name  \
1236  S0TX00217                                OPEN     PITTENGER, LELA MAE   
1584  S4NJ00201                                OPEN              HOLT, RUSH   
2152  S6NY00433                          CHALLENGER            MERCED, ALEX   
1496  S4MI00371                                OPEN    FULNER, ROBERT JAMES   
1503  S4MN00403                          CHALLENGER  TERRELL, KEVIN RICHARD   

     Cand_Office Cand_State  GE WINNER INDICATOR  Individual_Contribution  \
1236           S         TX                    0                  34764.0   
1584           S         NJ                    0                1224042.0   
2152           S         NY                    0                  12461.0   
1496           S         MI                    0                      0.0   
1503           S         MN                    0                   4343.0   

      Other_Committee_Contribution  Party_Committee_Contribution  \
1236                           0.0                         250.0   
1584                       19756.0                         500.0   
2152                        2000.0                           0.0   
1496                           0.0                           0.0   
1503                           0.0                           0.0   

      Total_Disbursement        ...          Cand_Office_St_SD  \
1236             51567.0        ...                          0   
1584           1744765.0        ...                          0   
2152             14459.0        ...                          0   
1496                 0.0        ...                          0   
1503             43054.0        ...                          0   

      Cand_Office_St_TN  Cand_Office_St_TX  Cand_Office_St_UT  \
1236                  0                  1                  0   
1584                  0                  0                  0   
2152                  0                  0                  0   
1496                  0                  0                  0   
1503                  0                  0                  0   

      Cand_Office_St_VA  Cand_Office_St_VT  Cand_Office_St_WA  \
1236                  0                  0                  0   
1584                  0                  0                  0   
2152                  0                  0                  0   
1496                  0                  0                  0   
1503                  0                  0                  0   

      Cand_Office_St_WI  Cand_Office_St_WV  Cand_Office_St_WY  
1236                  0                  0                  0  
1584                  0                  0                  0  
2152                  0                  0                  0  
1496                  0                  0                  0  
1503                  0                  0                  0  

[5 rows x 72 columns]

In [11]:
clf = RandomForestClassifier(n_estimators=200)
clf.fit(X,y)
X_test_3 = X_test.copy()
y_prob_3 = clf.predict_proba(X_test_3)[:,1]
print("Score: " + str(clf.score(X_test_3,y_test)))

Score: 0.9710144927536232


In [12]:
X_test_3["State"] = test_states
X_test_3["y_prob"] = y_prob_3

X_test_3["winner"] = 0
X_test_3.loc[X_test_3.groupby(['State'])["y_prob"].idxmax(),"winner"] = 1

print("AUC: " + str(roc_auc_score(y_test, y_prob_3)))

precision_recall_fscore_support(y_test, X_test_3["winner"])

AUC: 0.9855555555555556


(array([0.9844098 , 0.76470588]),
 array([0.98222222, 0.78787879]),
 array([0.98331479, 0.7761194 ]),
 array([450,  33], dtype=int64))

### For 4 years data (2016, 2014, 2012 and 2010)

In [13]:
senate_4 = senate[(senate["year"] == 2016) | (senate["year"] == 2014) | (senate["year"] == 2012) | (senate["year"] == 2010)].copy()

y = senate_4["GE WINNER INDICATOR"]
X = senate_4.drop(columns=["Cand_Id","Cand_Incumbent_Challenger_Open_Seat","Cand_Name","Cand_Office","Cand_State","GE WINNER INDICATOR","Individual_Contribution","Other_Committee_Contribution","Party_Committee_Contribution","Total_Disbursement","Total_Receipt","year"])

# print(y.value_counts())
print(X.shape)

senate_4.head()

(1957, 60)


Cand_Id Cand_Incumbent_Challenger_Open_Seat             Cand_Name  \
1236  S0TX00217                                OPEN   PITTENGER, LELA MAE   
1584  S4NJ00201                                OPEN            HOLT, RUSH   
487   S0IL00394                                OPEN       DORSEY, MICHAEL   
2152  S6NY00433                          CHALLENGER          MERCED, ALEX   
1496  S4MI00371                                OPEN  FULNER, ROBERT JAMES   

     Cand_Office Cand_State  GE WINNER INDICATOR  Individual_Contribution  \
1236           S         TX                    0                  34764.0   
1584           S         NJ                    0                1224042.0   
487            S         IL                    0                      0.0   
2152           S         NY                    0                  12461.0   
1496           S         MI                    0                      0.0   

      Other_Committee_Contribution  Party_Committee_Contribution  \
1236                           0.0                         250.0   
1584                       19756.0                         500.0   
487                            0.0                           0.0   
2152                        2000.0                           0.0   
1496                           0.0                           0.0   

      Total_Disbursement        ...          Cand_Office_St_SD  \
1236             51567.0        ...                          0   
1584           1744765.0        ...                          0   
487                107.0        ...                          0   
2152             14459.0        ...                          0   
1496                 0.0        ...                          0   

      Cand_Office_St_TN  Cand_Office_St_TX  Cand_Office_St_UT  \
1236                  0                  1                  0   
1584                  0                  0                  0   
487                   0                  0                  0   
2152                  0                  0                  0   
1496                  0                  0                  0   

      Cand_Office_St_VA  Cand_Office_St_VT  Cand_Office_St_WA  \
1236                  0                  0                  0   
1584                  0                  0                  0   
487                   0                  0                  0   
2152                  0                  0                  0   
1496                  0                  0                  0   

      Cand_Office_St_WI  Cand_Office_St_WV  Cand_Office_St_WY  
1236                  0                  0                  0  
1584                  0                  0                  0  
487                   0                  0                  0  
2152                  0                  0                  0  
1496                  0                  0                  0  

[5 rows x 72 columns]

In [14]:
clf = RandomForestClassifier(n_estimators=200)
clf.fit(X,y)
X_test_4 = X_test.copy()
y_prob_4 = clf.predict_proba(X_test_4)[:,1]
print("Score: " + str(clf.score(X_test_4,y_test)))

Score: 0.9627329192546584


In [15]:
X_test_4["State"] = test_states
X_test_4["y_prob"] = y_prob_4

X_test_4["winner"] = 0
X_test_4.loc[X_test_4.groupby(['State'])["y_prob"].idxmax(),"winner"] = 1

print("AUC: " + str(roc_auc_score(y_test, y_prob_4)))

precision_recall_fscore_support(y_test, X_test_4["winner"])

AUC: 0.9855555555555555


(array([0.98663697, 0.79411765]),
 array([0.98444444, 0.81818182]),
 array([0.98553949, 0.80597015]),
 array([450,  33], dtype=int64))

### For 5 years data (2016, 2014, 2012, 2010 and 2008)

In [16]:
senate_5 = senate[(senate["year"] == 2016) | (senate["year"] == 2014) | (senate["year"] == 2012) | (senate["year"] == 2010) | (senate["year"] == 2008)].copy()

y = senate_5["GE WINNER INDICATOR"]
X = senate_5.drop(columns=["Cand_Id","Cand_Incumbent_Challenger_Open_Seat","Cand_Name","Cand_Office","Cand_State","GE WINNER INDICATOR","Individual_Contribution","Other_Committee_Contribution","Party_Committee_Contribution","Total_Disbursement","Total_Receipt","year"])

# print(y.value_counts())
print(X.shape)

senate_5.head()

(2242, 60)


Cand_Id Cand_Incumbent_Challenger_Open_Seat            Cand_Name  \
1236  S0TX00217                                OPEN  PITTENGER, LELA MAE   
1584  S4NJ00201                                OPEN           HOLT, RUSH   
487   S0IL00394                                OPEN      DORSEY, MICHAEL   
2152  S6NY00433                          CHALLENGER         MERCED, ALEX   
255   S2TX00106                           INCUMBENT         CORNYN, JOHN   

     Cand_Office Cand_State  GE WINNER INDICATOR  Individual_Contribution  \
1236           S         TX                    0                  34764.0   
1584           S         NJ                    0                1224042.0   
487            S         IL                    0                      0.0   
2152           S         NY                    0                  12461.0   
255            S         TX                    1               10061260.0   

      Other_Committee_Contribution  Party_Committee_Contribution  \
1236                           0.0                         250.0   
1584                       19756.0                         500.0   
487                            0.0                           0.0   
2152                        2000.0                           0.0   
255                      2613361.0                           0.0   

      Total_Disbursement        ...          Cand_Office_St_SD  \
1236             51567.0        ...                          0   
1584           1744765.0        ...                          0   
487                107.0        ...                          0   
2152             14459.0        ...                          0   
255           16454518.0        ...                          0   

      Cand_Office_St_TN  Cand_Office_St_TX  Cand_Office_St_UT  \
1236                  0                  1                  0   
1584                  0                  0                  0   
487                   0                  0                  0   
2152                  0                  0                  0   
255                   0                  1                  0   

      Cand_Office_St_VA  Cand_Office_St_VT  Cand_Office_St_WA  \
1236                  0                  0                  0   
1584                  0                  0                  0   
487                   0                  0                  0   
2152                  0                  0                  0   
255                   0                  0                  0   

      Cand_Office_St_WI  Cand_Office_St_WV  Cand_Office_St_WY  
1236                  0                  0                  0  
1584                  0                  0                  0  
487                   0                  0                  0  
2152                  0                  0                  0  
255                   0                  0                  0  

[5 rows x 72 columns]

In [17]:
clf = RandomForestClassifier(n_estimators=200)
clf.fit(X,y)
X_test_5 = X_test.copy()
y_prob_5 = clf.predict_proba(X_test_5)[:,1]
print("Score: " + str(clf.score(X_test_5,y_test)))

Score: 0.9710144927536232


In [18]:
X_test_5["State"] = test_states
X_test_5["y_prob"] = y_prob_5

X_test_5["winner"] = 0
X_test_5.loc[X_test_5.groupby(['State'])["y_prob"].idxmax(),"winner"] = 1

print("AUC: " + str(roc_auc_score(y_test, y_prob_5)))

precision_recall_fscore_support(y_test, X_test_5["winner"])

AUC: 0.9854208754208755


(array([0.98886414, 0.82352941]),
 array([0.98666667, 0.84848485]),
 array([0.98776418, 0.8358209 ]),
 array([450,  33], dtype=int64))